name: d818_mobile_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  logger: ^1.4.0
  go_router: ^10.0.0
  dio: ^5.3.2
  iconsax: ^0.0.8
  pin_code_fields: ^8.0.1
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  cupertino_will_pop_scope: ^1.2.1
  flutter_paypal: ^0.2.0
  dropdown_button2: ^2.3.8
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  flutter_switch: ^0.3.2
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.1
  flutter_dotenv: ^5.1.0
  flutter_stripe: ^11.4.0
  fluttertoast: ^8.2.12
  http: ^0.13.6
  intl: ^0.18.1
  connectivity_plus: ^6.1.2

  provider: any
  webview_flutter: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  keystore_generator:

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/D818.png"
  min_sdk_android: 21 
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/.env

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Thin.ttf

    - family: FrederickatheGreat
      fonts:
        - asset: fonts/FrederickatheGreat-Regular.ttf
